/**
 * classic-catalog.ts — Catálogo Canônico das Obras Clássicas Teológicas do TheoSphere.
 * Gerado a partir das 89 obras e 45.092 trechos indexados ativamente no UserEmbedding.
 */

export interface ClassicWorkItem {
  id: string;
  gid: string;
  title: string;
  author: string;
  year: string;
  tradition: string;
  category:
    | 'comentarios'
    | 'sistematica'
    | 'patristica'
    | 'historia'
    | 'devocional'
    | 'referencia'
    | 'geral';
  language: 'pt' | 'en' | 'la';
  chunks: number;
  readUrl: string;
  summary: string;
  isIndexed: boolean;
}

export const CLASSIC_THEOLOGICAL_CATALOG: ClassicWorkItem[] = [
  {
    id: '59353',
    gid: '59353',
    title: 'Of the Imitation of Christ',
    author: 'Tomás de Kempis',
    year: '1380-1471',
    tradition: 'Devocional',
    category: 'devocional',
    language: 'en',
    chunks: 75,
    readUrl: 'https://www.gutenberg.org/ebooks/59353',
    summary:
      'Of the Imitation of Christ por Tomás de Kempis. Obra histórica de domínio público indexada com 75 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '77585',
    gid: '77585',
    title: 'Confessions of St. Augustine',
    author: 'Santo Agostinho',
    year: '354-430 d.C.',
    tradition: 'Patrística',
    category: 'patristica',
    language: 'en',
    chunks: 42,
    readUrl: 'https://www.gutenberg.org/ebooks/77585',
    summary:
      'Confessions of St. Augustine por Santo Agostinho. Obra histórica de domínio público indexada com 42 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '45304',
    gid: '45304',
    title: 'The City of God, Volume I',
    author: 'Santo Agostinho',
    year: '354-430 d.C.',
    tradition: 'Patrística',
    category: 'sistematica',
    language: 'en',
    chunks: 469,
    readUrl: 'https://www.gutenberg.org/ebooks/45304',
    summary:
      'The City of God, Volume I por Santo Agostinho. Obra histórica de domínio público indexada com 469 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '45305',
    gid: '45305',
    title: 'The City of God, Volume II',
    author: 'Santo Agostinho',
    year: '354-430 d.C.',
    tradition: 'Patrística',
    category: 'sistematica',
    language: 'en',
    chunks: 494,
    readUrl: 'https://www.gutenberg.org/ebooks/45305',
    summary:
      'The City of God, Volume II por Santo Agostinho. Obra histórica de domínio público indexada com 494 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '3296',
    gid: '3296',
    title: 'The Confessions of St. Augustine',
    author: 'Santo Agostinho',
    year: '354-430 d.C.',
    tradition: 'Patrística',
    category: 'patristica',
    language: 'en',
    chunks: 230,
    readUrl: 'https://www.gutenberg.org/ebooks/3296',
    summary:
      'The Confessions of St. Augustine por Santo Agostinho. Obra histórica de domínio público indexada com 230 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '45843',
    gid: '45843',
    title: 'Writings in Connection with the Donatist Controversy',
    author: 'Santo Agostinho',
    year: '354-430 d.C.',
    tradition: 'Patrística',
    category: 'patristica',
    language: 'en',
    chunks: 443,
    readUrl: 'https://www.gutenberg.org/ebooks/45843',
    summary:
      'Writings in Connection with the Donatist Controversy por Santo Agostinho. Obra histórica de domínio público indexada com 443 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '1967',
    gid: '1967',
    title: 'Morning and Evening',
    author: 'Balzac, Honoré de',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 156,
    readUrl: 'https://www.gutenberg.org/ebooks/1967',
    summary:
      'Morning and Evening por Balzac, Honoré de. Obra histórica de domínio público indexada com 156 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '41785',
    gid: '41785',
    title: 'Sermons on Several Occasions',
    author: 'Bayley, Harold',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 471,
    readUrl: 'https://www.gutenberg.org/ebooks/41785',
    summary:
      'Sermons on Several Occasions por Bayley, Harold. Obra histórica de domínio público indexada com 471 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '27530',
    gid: '27530',
    title: 'All of Grace',
    author: 'Brooke, L. Leslie (Leonard Leslie)',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 7,
    readUrl: 'https://www.gutenberg.org/ebooks/27530',
    summary:
      'All of Grace por Brooke, L. Leslie (Leonard Leslie). Obra histórica de domínio público indexada com 7 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '39452',
    gid: '39452',
    title: "The Pilgrim's Progress",
    author: 'John Bunyan',
    year: '1628-1688',
    tradition: 'Puritana',
    category: 'devocional',
    language: 'en',
    chunks: 206,
    readUrl: 'https://www.gutenberg.org/ebooks/39452',
    summary:
      "The Pilgrim's Progress por John Bunyan. Obra histórica de domínio público indexada com 206 trechos na base vetorial RAG do TheoSphere.",
    isIndexed: true,
  },
  {
    id: '45001',
    gid: '45001',
    title: 'Institutes of the Christian Religion Vol I',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'sistematica',
    language: 'en',
    chunks: 659,
    readUrl: 'https://www.gutenberg.org/ebooks/45001',
    summary:
      'Institutes of the Christian Religion Vol I por João Calvino. Obra histórica de domínio público indexada com 659 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '64392',
    gid: '64392',
    title: 'Institutes of the Christian Religion Vol II',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'sistematica',
    language: 'en',
    chunks: 679,
    readUrl: 'https://www.gutenberg.org/ebooks/64392',
    summary:
      'Institutes of the Christian Religion Vol II por João Calvino. Obra histórica de domínio público indexada com 679 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '45423',
    gid: '45423',
    title:
      'Letters of John Calvin, Volume I: Compiled from the Original Manuscripts and Edited with Historical Notes',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 383,
    readUrl: 'https://www.gutenberg.org/ebooks/45423',
    summary:
      'Letters of John Calvin, Volume I: Compiled from the Original Manuscripts and Edited with Historical Notes por João Calvino. Obra histórica de domínio público indexada com 383 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '45463',
    gid: '45463',
    title:
      'Letters of John Calvin, Volume II: Compiled from the Original Manuscripts and Edited with Historical Notes',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 363,
    readUrl: 'https://www.gutenberg.org/ebooks/45463',
    summary:
      'Letters of John Calvin, Volume II: Compiled from the Original Manuscripts and Edited with Historical Notes por João Calvino. Obra histórica de domínio público indexada com 363 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '19039',
    gid: '19039',
    title: 'Lectures to My Students',
    author: 'Cantù, Cesare',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 291,
    readUrl: 'https://www.gutenberg.org/ebooks/19039',
    summary:
      'Lectures to My Students por Cantù, Cesare. Obra histórica de domínio público indexada com 291 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '36907',
    gid: '36907',
    title: 'Cur Deus Homo (Why God Became Man)',
    author: 'Douglas, Amanda M.',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 136,
    readUrl: 'https://www.gutenberg.org/ebooks/36907',
    summary:
      'Cur Deus Homo (Why God Became Man) por Douglas, Amanda M.. Obra histórica de domínio público indexada com 136 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '14867',
    gid: '14867',
    title: 'A Treatise Concerning Religious Affections',
    author: 'Ellinwood, Frank F. (Frank Field)',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 220,
    readUrl: 'https://www.gutenberg.org/ebooks/14867',
    summary:
      'A Treatise Concerning Religious Affections por Ellinwood, Frank F. (Frank Field). Obra histórica de domínio público indexada com 220 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '2848',
    gid: '2848',
    title: 'The Antiquities of the Jews',
    author: 'Flávio Josefo',
    year: '37-100 d.C.',
    tradition: 'Histórica',
    category: 'historia',
    language: 'en',
    chunks: 317,
    readUrl: 'https://www.gutenberg.org/ebooks/2848',
    summary:
      'The Antiquities of the Jews por Flávio Josefo. Obra histórica de domínio público indexada com 317 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '2850',
    gid: '2850',
    title: 'The Wars of the Jews',
    author: 'Flávio Josefo',
    year: '37-100 d.C.',
    tradition: 'Histórica',
    category: 'historia',
    language: 'en',
    chunks: 473,
    readUrl: 'https://www.gutenberg.org/ebooks/2850',
    summary:
      'The Wars of the Jews por Flávio Josefo. Obra histórica de domínio público indexada com 473 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '7098',
    gid: '7098',
    title: 'Apology',
    author: 'Tomás de Aquino',
    year: '1225-1274',
    tradition: 'Escolástica',
    category: 'sistematica',
    language: 'en',
    chunks: 108,
    readUrl: 'https://www.gutenberg.org/ebooks/7098',
    summary:
      'Apology por Tomás de Aquino. Obra histórica de domínio público indexada com 108 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '654',
    gid: '654',
    title: 'Grace Abounding to the Chief of Sinners',
    author: 'John Bunyan',
    year: '1628-1688',
    tradition: 'Puritana',
    category: 'devocional',
    language: 'en',
    chunks: 118,
    readUrl: 'https://www.gutenberg.org/ebooks/654',
    summary:
      'Grace Abounding to the Chief of Sinners por John Bunyan. Obra histórica de domínio público indexada com 118 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '395',
    gid: '395',
    title: 'The Holy War',
    author: 'John Bunyan',
    year: '1628-1688',
    tradition: 'Puritana',
    category: 'devocional',
    language: 'en',
    chunks: 199,
    readUrl: 'https://www.gutenberg.org/ebooks/395',
    summary:
      'The Holy War por John Bunyan. Obra histórica de domínio público indexada com 199 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91036',
    gid: '91036',
    title: 'Acts of the Apostles Vol 1',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 426,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Acts of the Apostles Vol 1 por João Calvino. Obra histórica de domínio público indexada com 426 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91037',
    gid: '91037',
    title: 'Acts of the Apostles Vol 2',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 332,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Acts of the Apostles Vol 2 por João Calvino. Obra histórica de domínio público indexada com 332 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91039',
    gid: '91039',
    title: 'Commentary on 1 Corinthians',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 421,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on 1 Corinthians por João Calvino. Obra histórica de domínio público indexada com 421 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91040',
    gid: '91040',
    title: 'Commentary on 2 Corinthians',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 381,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on 2 Corinthians por João Calvino. Obra histórica de domínio público indexada com 381 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91045',
    gid: '91045',
    title: 'Commentary on Catholic Epistles',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 400,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on Catholic Epistles por João Calvino. Obra histórica de domínio público indexada com 400 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91041',
    gid: '91041',
    title: 'Commentary on Galatians and Ephesians',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 296,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on Galatians and Ephesians por João Calvino. Obra histórica de domínio público indexada com 296 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91001',
    gid: '91001',
    title: 'Commentary on Genesis Vol 1',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 480,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on Genesis Vol 1 por João Calvino. Obra histórica de domínio público indexada com 480 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91002',
    gid: '91002',
    title: 'Commentary on Genesis Vol 2',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 433,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on Genesis Vol 2 por João Calvino. Obra histórica de domínio público indexada com 433 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91044',
    gid: '91044',
    title: 'Commentary on Hebrews',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 370,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on Hebrews por João Calvino. Obra histórica de domínio público indexada com 370 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91017',
    gid: '91017',
    title: 'Commentary on Jeremiah and Lamentations Vol 1',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 453,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on Jeremiah and Lamentations Vol 1 por João Calvino. Obra histórica de domínio público indexada com 453 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91018',
    gid: '91018',
    title: 'Commentary on Jeremiah and Lamentations Vol 2',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 406,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on Jeremiah and Lamentations Vol 2 por João Calvino. Obra histórica de domínio público indexada com 406 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91019',
    gid: '91019',
    title: 'Commentary on Jeremiah and Lamentations Vol 3',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 412,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on Jeremiah and Lamentations Vol 3 por João Calvino. Obra histórica de domínio público indexada com 412 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91020',
    gid: '91020',
    title: 'Commentary on Jeremiah and Lamentations Vol 4',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 551,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on Jeremiah and Lamentations Vol 4 por João Calvino. Obra histórica de domínio público indexada com 551 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91021',
    gid: '91021',
    title: 'Commentary on Jeremiah and Lamentations Vol 5',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 455,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on Jeremiah and Lamentations Vol 5 por João Calvino. Obra histórica de domínio público indexada com 455 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91042',
    gid: '91042',
    title: 'Commentary on Philippians, Colossians, and Thessalonians',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 313,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on Philippians, Colossians, and Thessalonians por João Calvino. Obra histórica de domínio público indexada com 313 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91038',
    gid: '91038',
    title: 'Commentary on Romans',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 538,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on Romans por João Calvino. Obra histórica de domínio público indexada com 538 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91007',
    gid: '91007',
    title: 'Commentary on the Book of Joshua',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 285,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Book of Joshua por João Calvino. Obra histórica de domínio público indexada com 285 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91008',
    gid: '91008',
    title: 'Commentary on the Book of Psalms Vol 1',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 536,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Book of Psalms Vol 1 por João Calvino. Obra histórica de domínio público indexada com 536 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91009',
    gid: '91009',
    title: 'Commentary on the Book of Psalms Vol 2',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 417,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Book of Psalms Vol 2 por João Calvino. Obra histórica de domínio público indexada com 417 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91010',
    gid: '91010',
    title: 'Commentary on the Book of Psalms Vol 3',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 447,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Book of Psalms Vol 3 por João Calvino. Obra histórica de domínio público indexada com 447 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91011',
    gid: '91011',
    title: 'Commentary on the Book of Psalms Vol 4',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 427,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Book of Psalms Vol 4 por João Calvino. Obra histórica de domínio público indexada com 427 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91012',
    gid: '91012',
    title: 'Commentary on the Book of Psalms Vol 5',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 378,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Book of Psalms Vol 5 por João Calvino. Obra histórica de domínio público indexada com 378 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91026',
    gid: '91026',
    title: 'Commentary on the Minor Prophets (Hosea) Vol 1',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 422,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Minor Prophets (Hosea) Vol 1 por João Calvino. Obra histórica de domínio público indexada com 422 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91027',
    gid: '91027',
    title: 'Commentary on the Minor Prophets (Joel, Amos, Obadiah) Vol 2',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 350,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Minor Prophets (Joel, Amos, Obadiah) Vol 2 por João Calvino. Obra histórica de domínio público indexada com 350 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91024',
    gid: '91024',
    title: 'Commentary on the Prophet Daniel Vol 1',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 366,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Prophet Daniel Vol 1 por João Calvino. Obra histórica de domínio público indexada com 366 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91025',
    gid: '91025',
    title: 'Commentary on the Prophet Daniel Vol 2',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 387,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Prophet Daniel Vol 2 por João Calvino. Obra histórica de domínio público indexada com 387 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91022',
    gid: '91022',
    title: 'Commentary on the Prophet Ezekiel Vol 1',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 328,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Prophet Ezekiel Vol 1 por João Calvino. Obra histórica de domínio público indexada com 328 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91023',
    gid: '91023',
    title: 'Commentary on the Prophet Ezekiel Vol 2',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 368,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Prophet Ezekiel Vol 2 por João Calvino. Obra histórica de domínio público indexada com 368 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91013',
    gid: '91013',
    title: 'Commentary on the Prophet Isaiah Vol 1',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 430,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Prophet Isaiah Vol 1 por João Calvino. Obra histórica de domínio público indexada com 430 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91014',
    gid: '91014',
    title: 'Commentary on the Prophet Isaiah Vol 2',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 392,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Prophet Isaiah Vol 2 por João Calvino. Obra histórica de domínio público indexada com 392 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91015',
    gid: '91015',
    title: 'Commentary on the Prophet Isaiah Vol 3',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 432,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Prophet Isaiah Vol 3 por João Calvino. Obra histórica de domínio público indexada com 432 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91016',
    gid: '91016',
    title: 'Commentary on the Prophet Isaiah Vol 4',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 385,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Prophet Isaiah Vol 4 por João Calvino. Obra histórica de domínio público indexada com 385 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91043',
    gid: '91043',
    title: 'Commentary on Timothy, Titus, and Philemon',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 307,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on Timothy, Titus, and Philemon por João Calvino. Obra histórica de domínio público indexada com 307 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91034',
    gid: '91034',
    title: 'Gospel According to John Vol 1',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 373,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Gospel According to John Vol 1 por João Calvino. Obra histórica de domínio público indexada com 373 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91035',
    gid: '91035',
    title: 'Gospel According to John Vol 2',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 248,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Gospel According to John Vol 2 por João Calvino. Obra histórica de domínio público indexada com 248 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91003',
    gid: '91003',
    title: 'Harmony of Exodus, Leviticus, Numbers, Deuteronomy Vol 1',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 424,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Harmony of Exodus, Leviticus, Numbers, Deuteronomy Vol 1 por João Calvino. Obra histórica de domínio público indexada com 424 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91031',
    gid: '91031',
    title: 'Harmony of the Gospels Vol 1 (Matt, Mark, Luke)',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 436,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Harmony of the Gospels Vol 1 (Matt, Mark, Luke) por João Calvino. Obra histórica de domínio público indexada com 436 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91032',
    gid: '91032',
    title: 'Harmony of the Gospels Vol 2',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 406,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Harmony of the Gospels Vol 2 por João Calvino. Obra histórica de domínio público indexada com 406 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91033',
    gid: '91033',
    title: 'Harmony of the Gospels Vol 3',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 336,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Harmony of the Gospels Vol 3 por João Calvino. Obra histórica de domínio público indexada com 336 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91004',
    gid: '91004',
    title: 'Harmony of the Pentateuch Vol 2',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 421,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Harmony of the Pentateuch Vol 2 por João Calvino. Obra histórica de domínio público indexada com 421 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91005',
    gid: '91005',
    title: 'Harmony of the Pentateuch Vol 3',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 402,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Harmony of the Pentateuch Vol 3 por João Calvino. Obra histórica de domínio público indexada com 402 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '91006',
    gid: '91006',
    title: 'Harmony of the Pentateuch Vol 4',
    author: 'João Calvino',
    year: '1509-1564',
    tradition: 'Reformada',
    category: 'comentarios',
    language: 'en',
    chunks: 347,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Harmony of the Pentateuch Vol 4 por João Calvino. Obra histórica de domínio público indexada com 347 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '19038',
    gid: '19038',
    title: 'Homilies on the Gospel of St. John',
    author: 'João Crisóstomo',
    year: '349-407 d.C.',
    tradition: 'Patrística',
    category: 'patristica',
    language: 'en',
    chunks: 15,
    readUrl: 'https://www.gutenberg.org/ebooks/19038',
    summary:
      'Homilies on the Gospel of St. John por João Crisóstomo. Obra histórica de domínio público indexada com 15 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '22400',
    gid: '22400',
    title: "Foxe's Book of Martyrs",
    author: 'John Foxe',
    year: '1516-1587',
    tradition: 'Histórica',
    category: 'historia',
    language: 'en',
    chunks: 529,
    readUrl: 'https://www.gutenberg.org/ebooks/22400',
    summary:
      "Foxe's Book of Martyrs por John Foxe. Obra histórica de domínio público indexada com 529 trechos na base vetorial RAG do TheoSphere.",
    isIndexed: true,
  },
  {
    id: '32011',
    gid: '32011',
    title: 'Sinners in the Hands of an Angry God',
    author: 'Knight, Damon',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 20,
    readUrl: 'https://www.gutenberg.org/ebooks/32011',
    summary:
      'Sinners in the Hands of an Angry God por Knight, Damon. Obra histórica de domínio público indexada com 20 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '1670',
    gid: '1670',
    title: "Luther's Little Instruction Book: The Small Catechism",
    author: 'Martinho Lutero',
    year: '1483-1546',
    tradition: 'Luterana',
    category: 'sistematica',
    language: 'en',
    chunks: 15,
    readUrl: 'https://www.gutenberg.org/ebooks/1670',
    summary:
      "Luther's Little Instruction Book: The Small Catechism por Martinho Lutero. Obra histórica de domínio público indexada com 15 trechos na base vetorial RAG do TheoSphere.",
    isIndexed: true,
  },
  {
    id: '1722',
    gid: '1722',
    title: "Martin Luther's Large Catechism",
    author: 'Martinho Lutero',
    year: '1483-1546',
    tradition: 'Luterana',
    category: 'sistematica',
    language: 'en',
    chunks: 103,
    readUrl: 'https://www.gutenberg.org/ebooks/1722',
    summary:
      "Martin Luther's Large Catechism por Martinho Lutero. Obra histórica de domínio público indexada com 103 trechos na base vetorial RAG do TheoSphere.",
    isIndexed: true,
  },
  {
    id: '90007',
    gid: '90007',
    title: "Easton's Bible Dictionary",
    author: 'M.G. Easton',
    year: '1823-1894',
    tradition: 'Referência',
    category: 'referencia',
    language: 'en',
    chunks: 901,
    readUrl: 'https://www.ccel.org/',
    summary:
      "Easton's Bible Dictionary por M.G. Easton. Obra histórica de domínio público indexada com 901 trechos na base vetorial RAG do TheoSphere.",
    isIndexed: true,
  },
  {
    id: '3239',
    gid: '3239',
    title: 'The Stromata (Miscellanies)',
    author: 'MacGrath, Harold',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 218,
    readUrl: 'https://www.gutenberg.org/ebooks/3239',
    summary:
      'The Stromata (Miscellanies) por MacGrath, Harold. Obra histórica de domínio público indexada com 218 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '3390',
    gid: '3390',
    title: 'Commentary on the Epistle to the Galatians',
    author: 'Martinho Lutero',
    year: '1483-1546',
    tradition: 'Luterana',
    category: 'comentarios',
    language: 'en',
    chunks: 55,
    readUrl: 'https://www.gutenberg.org/ebooks/3390',
    summary:
      'Commentary on the Epistle to the Galatians por Martinho Lutero. Obra histórica de domínio público indexada com 55 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '90001',
    gid: '90001',
    title: 'Commentary on the Whole Bible',
    author: 'Matthew Henry',
    year: '1662-1714',
    tradition: 'Puritana',
    category: 'comentarios',
    language: 'en',
    chunks: 1,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Whole Bible por Matthew Henry. Obra histórica de domínio público indexada com 1 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '90001',
    gid: '90001',
    title: 'Commentary on the Whole Bible Vol 1',
    author: 'Matthew Henry',
    year: '1662-1714',
    tradition: 'Puritana',
    category: 'comentarios',
    language: 'en',
    chunks: 1871,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Whole Bible Vol 1 por Matthew Henry. Obra histórica de domínio público indexada com 1871 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '90002',
    gid: '90002',
    title: 'Commentary on the Whole Bible Vol 2',
    author: 'Matthew Henry',
    year: '1662-1714',
    tradition: 'Puritana',
    category: 'comentarios',
    language: 'en',
    chunks: 2388,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Whole Bible Vol 2 por Matthew Henry. Obra histórica de domínio público indexada com 2388 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '90003',
    gid: '90003',
    title: 'Commentary on the Whole Bible Vol 3',
    author: 'Matthew Henry',
    year: '1662-1714',
    tradition: 'Puritana',
    category: 'comentarios',
    language: 'en',
    chunks: 2457,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Whole Bible Vol 3 por Matthew Henry. Obra histórica de domínio público indexada com 2457 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '90004',
    gid: '90004',
    title: 'Commentary on the Whole Bible Vol 4',
    author: 'Matthew Henry',
    year: '1662-1714',
    tradition: 'Puritana',
    category: 'comentarios',
    language: 'en',
    chunks: 3220,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Whole Bible Vol 4 por Matthew Henry. Obra histórica de domínio público indexada com 3220 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '90005',
    gid: '90005',
    title: 'Commentary on the Whole Bible Vol 5',
    author: 'Matthew Henry',
    year: '1662-1714',
    tradition: 'Puritana',
    category: 'comentarios',
    language: 'en',
    chunks: 2650,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Whole Bible Vol 5 por Matthew Henry. Obra histórica de domínio público indexada com 2650 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '90006',
    gid: '90006',
    title: 'Commentary on the Whole Bible Vol 6',
    author: 'Matthew Henry',
    year: '1662-1714',
    tradition: 'Puritana',
    category: 'comentarios',
    language: 'en',
    chunks: 2504,
    readUrl: 'https://www.ccel.org/',
    summary:
      'Commentary on the Whole Bible Vol 6 por Matthew Henry. Obra histórica de domínio público indexada com 2504 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '59789',
    gid: '59789',
    title: 'The Works of John Wesley, Vol 1',
    author: 'Morton, Samuel George',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 75,
    readUrl: 'https://www.gutenberg.org/ebooks/59789',
    summary:
      'The Works of John Wesley, Vol 1 por Morton, Samuel George. Obra histórica de domínio público indexada com 75 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '9804',
    gid: '9804',
    title: 'Against Heresies',
    author: 'Ruskin, John',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 151,
    readUrl: 'https://www.gutenberg.org/ebooks/9804',
    summary:
      'Against Heresies por Ruskin, John. Obra histórica de domínio público indexada com 151 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '45844',
    gid: '45844',
    title: 'Anti-Pelagian Writings',
    author: 'Shedd, E. Cutler (Ephraim Cutler)',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 59,
    readUrl: 'https://www.gutenberg.org/ebooks/45844',
    summary:
      'Anti-Pelagian Writings por Shedd, E. Cutler (Ephraim Cutler). Obra histórica de domínio público indexada com 59 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '32055',
    gid: '32055',
    title: 'On the Priesthood',
    author: 'Sohl, Jerry',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 15,
    readUrl: 'https://www.gutenberg.org/ebooks/32055',
    summary:
      'On the Priesthood por Sohl, Jerry. Obra histórica de domínio público indexada com 15 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '17611',
    gid: '17611',
    title: 'Summa Theologica, Part I (Prima Pars)',
    author: 'Tomás de Aquino',
    year: '1225-1274',
    tradition: 'Escolástica',
    category: 'sistematica',
    language: 'en',
    chunks: 1009,
    readUrl: 'https://www.gutenberg.org/ebooks/17611',
    summary:
      'Summa Theologica, Part I (Prima Pars) por Tomás de Aquino. Obra histórica de domínio público indexada com 1009 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '17897',
    gid: '17897',
    title: 'Summa Theologica, Part I (Prima Pars)',
    author: 'Tomás de Aquino',
    year: '1225-1274',
    tradition: 'Escolástica',
    category: 'sistematica',
    language: 'en',
    chunks: 1014,
    readUrl: 'https://www.gutenberg.org/ebooks/17897',
    summary:
      'Summa Theologica, Part I (Prima Pars) por Tomás de Aquino. Obra histórica de domínio público indexada com 1014 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '18755',
    gid: '18755',
    title: 'Summa Theologica, Part II-I',
    author: 'Tomás de Aquino',
    year: '1225-1274',
    tradition: 'Escolástica',
    category: 'sistematica',
    language: 'en',
    chunks: 1463,
    readUrl: 'https://www.gutenberg.org/ebooks/18755',
    summary:
      'Summa Theologica, Part II-I por Tomás de Aquino. Obra histórica de domínio público indexada com 1463 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '19950',
    gid: '19950',
    title: 'Summa Theologica, Part III (Tertia Pars)',
    author: 'Tomás de Aquino',
    year: '1225-1274',
    tradition: 'Escolástica',
    category: 'sistematica',
    language: 'en',
    chunks: 965,
    readUrl: 'https://www.gutenberg.org/ebooks/19950',
    summary:
      'Summa Theologica, Part III (Tertia Pars) por Tomás de Aquino. Obra histórica de domínio público indexada com 965 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '17723',
    gid: '17723',
    title: 'Homilies on the Epistles of Paul to the Corinthians',
    author: 'Various',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 79,
    readUrl: 'https://www.gutenberg.org/ebooks/17723',
    summary:
      'Homilies on the Epistles of Paul to the Corinthians por Various. Obra histórica de domínio público indexada com 79 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
  {
    id: '32999',
    gid: '32999',
    title: 'On the Incarnation of the Word',
    author: 'Various',
    year: 'Séc. XVI-XVIII',
    tradition: 'Clássica',
    category: 'devocional',
    language: 'en',
    chunks: 59,
    readUrl: 'https://www.gutenberg.org/ebooks/32999',
    summary:
      'On the Incarnation of the Word por Various. Obra histórica de domínio público indexada com 59 trechos na base vetorial RAG do TheoSphere.',
    isIndexed: true,
  },
];
