/**
 * Classic Commentaries (Public Domain).
 *
 * Extracted from RagService to keep the service logic clean.
 */

export interface ClassicCommentary {
  id: string;
  reference: string;
  author: string;
  work: string;
  year: string;
  tradition: string;
  text: string;
  keywords?: string[];
}

export const CLASSIC_COMMENTARIES: ClassicCommentary[] = [
  {
    id: 'calvin-john-3-16',
    reference: 'João 3:16',
    author: 'João Calvino',
    work: 'Comentários sobre o Evangelho de João',
    year: '1553',
    tradition: 'Reformada',
    text: "Pois Deus amou o mundo de tal maneira. O mundo aqui se refere não apenas aos judeus, mas a todos os povos da terra. Ele usa o termo 'mundo' para que ninguém seja excluído, desde que acredite. Contudo, foi necessário acrescentar 'todo aquele que nele crê', pois nem todos recebem Cristo por fé.",
  },
  {
    id: 'henry-john-3-16',
    reference: 'João 3:16',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: 'God so loved the world — the whole race of mankind. He gave his only-begotten Son — not a servant, not an angel, but his Son. The condition required is only believing in him. Hell is perishing; heaven is everlasting life.',
  },
  {
    id: 'spurgeon-john-3-16',
    reference: 'João 3:16',
    author: 'Charles Spurgeon',
    work: 'Metropolitan Tabernacle Pulpit',
    year: '1885',
    tradition: 'Batista Particular',
    text: 'God so loved the world — so, so greatly, so wonderfully, so immeasurably. Whosoever believeth in him — a world-wide word, not a select few. He that believes shall not perish. O the width and depth of this golden text!',
  },
  {
    id: 'wesley-john-3-16',
    reference: 'João 3:16',
    author: 'John Wesley',
    work: 'Explanatory Notes upon the New Testament',
    year: '1755',
    tradition: 'Arminiana',
    text: 'God so loved the world — all men under heaven; both Jews and Gentiles. Gave his only-begotten Son. Whosoever believeth in him — the most comprehensive term possible — whosoever, without any exception.',
  },
  {
    id: 'barnes-john-3-16',
    reference: 'João 3:16',
    author: 'Albert Barnes',
    work: "Barnes' Notes on the New Testament",
    year: '1832',
    tradition: 'Presbiteriana',
    text: "The word 'world' cannot be limited to the elect or to any particular people. God so loved it so much, in such a way, that he gave his only-begotten Son. Perish denotes punishment and destruction, as opposed to the everlasting life promised to believers.",
  },
  {
    id: 'calvin-john-1-1',
    reference: 'João 1:1',
    author: 'João Calvino',
    work: 'Comentários sobre o Evangelho de João',
    year: '1553',
    tradition: 'Reformada',
    text: "No princípio era o Verbo — João afirma que o Verbo existia antes que o mundo fosse criado. 'Era' aqui significa existência eterna. E o Verbo era Deus — João afirma de forma absoluta que ele é Deus, participando de toda a essência divina.",
  },
  {
    id: 'henry-john-1-1',
    reference: 'João 1:1',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: 'In the beginning was the Word — Before all time, before the world was. The Word was God — not a subordinate deity, but truly and essentially God, of the same substance with the Father.',
  },
  {
    id: 'henry-romans-3-23',
    reference: 'Romanos 3:23',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: 'All have sinned and come short of the glory of God — This is a universal charge. None is excepted. Jews and Gentiles alike stand guilty. This verse destroys all presumption of human merit.',
  },
  {
    id: 'calvin-romans-3-23',
    reference: 'Romanos 3:23',
    author: 'João Calvino',
    work: 'Comentários sobre Romanos',
    year: '1540',
    tradition: 'Reformada',
    text: 'Todos pecaram e estão privados da glória de Deus. Paulo afirma que todos os homens estão sujeitos à condenação, sem nenhuma exceção. Este versículo destrói toda presunção de mérito humano.',
  },
  {
    id: 'henry-romans-5-8',
    reference: 'Romanos 5:8',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us. The commendation of God's love consists in this very contrast: such worthless objects, such unspeakable love.",
  },
  {
    id: 'spurgeon-romans-5-8',
    reference: 'Romanos 5:8',
    author: 'Charles Spurgeon',
    work: 'Metropolitan Tabernacle Pulpit',
    year: '1871',
    tradition: 'Batista Particular',
    text: "While we were yet sinners — there is the wonder. Not while we were saints, but while we were rebels, traitors, enemies. The cross is God's argument against despair.",
  },
  {
    id: 'gill-romans-8-28',
    reference: 'Romanos 8:28',
    author: 'John Gill',
    work: 'Exposition of the Entire Bible',
    year: '1763',
    tradition: 'Batista Calvinista',
    text: 'All things work together for good — not each one in isolation but in their combined operation under divine Providence. Even afflictions and trials are made to subserve the best interests of the elect.',
  },
  {
    id: 'wesley-romans-8-28',
    reference: 'Romanos 8:28',
    author: 'John Wesley',
    work: 'Explanatory Notes upon the New Testament',
    year: '1755',
    tradition: 'Arminiana',
    text: 'To them that love God — all who love God have an inward conviction that their afflictions will result to their final benefit. God works all things — even tribulations — for the spiritual and eternal benefit of his children.',
  },
  {
    id: 'spurgeon-romans-8-38-39',
    reference: 'Romanos 8:38-39',
    author: 'Charles Spurgeon',
    work: 'Metropolitan Tabernacle Pulpit',
    year: '1869',
    tradition: 'Batista Particular',
    text: 'Paul piles mountain upon mountain — death, life, angels, principalities, powers, things present, things to come — and challenges them all. None can sever the bond between Christ and his redeemed. We may be separated from comfort, but never from the love of God which is in Christ Jesus.',
  },
  {
    id: 'henry-genesis-1-1',
    reference: 'Gênesis 1:1',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: 'In the beginning God created the heaven and the earth. It demolishes atheism, polytheism, and eternal matter. The origin of all things was not by chance, not by necessity, but by the free act of an infinite, eternal, and all-powerful God.',
  },
  {
    id: 'calvin-genesis-1-1',
    reference: 'Gênesis 1:1',
    author: 'João Calvino',
    work: 'Comentários sobre o Gênesis',
    year: '1554',
    tradition: 'Reformada',
    text: "No princípio criou Deus os céus e a terra. A palavra hebraica 'bara' designa criação a partir do nada. Este versículo revela que o mundo tem uma idade: ele teve um início, não existiu desde sempre.",
  },
  {
    id: 'calvin-ephesians-2-8-9',
    reference: 'Efésios 2:8-9',
    author: 'João Calvino',
    work: 'Comentários sobre Efésios',
    year: '1548',
    tradition: 'Reformada',
    text: 'Pela graça sois salvos, por meio da fé. Paulo está aqui excluindo completamente todo mérito humano da salvação. Mesmo a fé em si é um dom de Deus — operada pelo Espírito Santo no coração do eleito.',
  },
  {
    id: 'henry-ephesians-2-8-9',
    reference: 'Efésios 2:8-9',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: 'For by grace are ye saved through faith — Grace is the fountain; faith is the channel. The very faith by which we embrace Christ is not of ourselves; it is the gift of God. Not of works, lest any man should boast.',
  },
  {
    id: 'spurgeon-ephesians-2-8-9',
    reference: 'Efésios 2:8-9',
    author: 'Charles Spurgeon',
    work: 'Metropolitan Tabernacle Pulpit',
    year: '1858',
    tradition: 'Batista Particular',
    text: "Salvation is of grace — pure, sovereign, undeserved, unearned grace. Not of works, lest any man should boast. In heaven every voice will sing: 'Worthy is the Lamb.'",
  },
  {
    id: 'henry-hebrews-11-1',
    reference: 'Hebreus 11:1',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: 'Faith is the substance of things hoped for — the firm ground on which we stand. The evidence of things not seen — it is the spiritual sense which discerns spiritual realities, as the eye discerns material objects.',
  },
  {
    id: 'spurgeon-hebrews-11-1',
    reference: 'Hebreus 11:1',
    author: 'Charles Spurgeon',
    work: 'Metropolitan Tabernacle Pulpit',
    year: '1866',
    tradition: 'Batista Particular',
    text: "Faith is the substance of things hoped for — it gives a present reality to future blessings. The evidence of things not seen — faith is God's own gift of sight for the invisible world.",
  },
  {
    id: 'henry-psalms-23-1',
    reference: 'Salmos 23:1',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: 'The Lord is my shepherd — implies dependence, guidance, and care. I shall not want — He who has God for his shepherd is in the best keeping; he is sure to want nothing that is truly good for him.',
  },
  {
    id: 'spurgeon-psalms-23-1',
    reference: 'Salmos 23:1',
    author: 'Charles Spurgeon',
    work: 'The Treasury of David',
    year: '1865',
    tradition: 'Batista Particular',
    text: 'The Lord is my shepherd — what a title! Jehovah-Rohi. I shall not want — a golden sentence of the most comprehensive kind. If Jehovah is my shepherd, then need, hunger, danger, loneliness, and death are all vanquished.',
  },
  {
    id: 'henry-isaiah-53-5',
    reference: 'Isaías 53:5',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: 'He was wounded for our transgressions — this is the heart of the gospel. The legal punishment of our sins fell upon the innocent Lamb of God, so that justice might be satisfied and mercy might flow to us.',
  },
  {
    id: 'spurgeon-isaiah-53-5',
    reference: 'Isaías 53:5',
    author: 'Charles Spurgeon',
    work: 'Metropolitan Tabernacle Pulpit',
    year: '1877',
    tradition: 'Batista Particular',
    text: 'Wounded for our transgressions — not for his own; he had none. Substitution stands here as plain as language can make it. By his stripes we are healed — our spiritual disease is cured by his physical agony.',
  },
  {
    id: 'henry-1cor-13-4-7',
    reference: '1 Coríntios 13:4-7',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: 'Charity suffereth long, is kind, envieth not, vaunteth not itself, is not puffed up. Beareth all things, endureth all things. This is a portrait of Christ himself — and of what every Christian should aspire to become.',
  },
  {
    id: 'henry-philippians-4-13',
    reference: 'Filipenses 4:13',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: 'I can do all things through Christ which strengtheneth me. The context is contentment and sufficiency amid various circumstances. Through Christ — not through his own resolution or stoicism, but through a living union with Christ.',
  },
  {
    id: 'spurgeon-philippians-4-13',
    reference: 'Filipenses 4:13',
    author: 'Charles Spurgeon',
    work: 'Metropolitan Tabernacle Pulpit',
    year: '1876',
    tradition: 'Batista Particular',
    text: 'I can do all things — through Christ which strengtheneth me. Without Christ he could do nothing; with Christ he could do everything needful. To be content in prison and in palace, hungry and well-fed — this requires a strength that comes only from above.',
  },
  {
    id: 'henry-jeremiah-29-11',
    reference: 'Jeremias 29:11',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: "For I know the thoughts that I think toward you — spoken to the Jewish exiles in Babylon. God assures them that even in their exile his plans were of hope. God's thoughts toward his people are not of evil; the darkest providences conceal the brightest purposes.",
  },
  {
    id: 'henry-matthew-5-3-12',
    reference: 'Mateus 5:3-12',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: 'Blessed are the poor in spirit — poverty of spirit is a deep sense of our own spiritual poverty; an emptiness of self-sufficiency and pride. The kingdom of heaven is theirs. The Beatitudes describe the graces which all Christians should possess in their fullest development.',
  },
  {
    id: 'spurgeon-matthew-5-3-12',
    reference: 'Mateus 5:3-12',
    author: 'Charles Spurgeon',
    work: 'Metropolitan Tabernacle Pulpit',
    year: '1872',
    tradition: 'Batista Particular',
    text: "Christ opens with eight beatitudes. The world calls the poor, the mourning, and the persecuted unhappy; Christ calls them blessed. He turns the world's value system upside down, as the kingdom of God always does.",
    keywords: ['bem-aventuranças', 'mateus 5', 'sermão do monte'],
  },
  {
    id: 'henry-matthew-6-9',
    reference: 'Mateus 6:9-13',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: "The Lord's Prayer is a pattern for all our prayers. 'Our Father' - we come as children to a father. 'Hallowed be thy name' - the glory of God is our first concern. It is short, yet comprehensive; simple, yet profound.",
    keywords: ['pai nosso', 'oração', 'mateus 6'],
  },
  {
    id: 'calvin-matthew-28-19',
    reference: 'Mateus 28:18-20',
    author: 'João Calvino',
    work: 'Comentários sobre a Harmonia dos Evangelhos',
    year: '1555',
    tradition: 'Reformada',
    text: 'Ide e fazei discípulos de todas as nações. Cristo afirma Sua autoridade universal antes de enviar os apóstolos. O batismo em nome do Pai, Filho e Espírito Santo é o selo da nossa inserção no corpo de Cristo e na verdade da Trindade.',
    keywords: ['grande comissão', 'missões', 'batismo', 'trindade'],
  },
  {
    id: 'henry-ephesians-6-11',
    reference: 'Efésios 6:10-18',
    author: 'Matthew Henry',
    work: 'Commentary on the Whole Bible',
    year: '1706',
    tradition: 'Puritana',
    text: 'Put on the whole armour of God. We have a powerful enemy, but God has provided sufficient defense. The belt of truth, the breastplate of righteousness, the shield of faith - these are not physical, but spiritual graces derived from Christ.',
    keywords: ['armadura de deus', 'batalha espiritual', 'efésios 6'],
  },
  {
    id: 'calvin-2tim-3-16',
    reference: '2 Timóteo 3:16',
    author: 'João Calvino',
    work: 'Comentários sobre as Epístolas Pastorais',
    year: '1548',
    tradition: 'Reformada',
    text: 'Toda a Escritura é divinamente inspirada. Isto significa que a Bíblia não procedeu do cérebro de homens, mas foi ditada pelo Espírito Santo. Ela é a regra perfeita de fé e prática, útil para o ensino e correção.',
    keywords: ['inspiração', 'escritura', 'bíblia', 'autoridade'],
  },
];
