/**
 * Mapa canônico nome-do-livro → bookId (1–66), PT-BR e EN.
 *
 * Extraído de search.service.ts na auditoria de 2026-07-21: o mesmo mapa
 * existia duplicado duas vezes no serviço (reference-detection e
 * resolveBookId), com variantes EN faltando em uma das cópias
 * ("1 corinthians", "1 peter", etc. não resolviam no reference-detection).
 * Fonte única daqui em diante.
 */
export const BOOK_NAME_TO_ID: Record<string, number> = {
  // ── Antigo Testamento ───────────────────────────────────────────────
  gênesis: 1,
  genesis: 1,
  êxodo: 2,
  exodus: 2,
  levítico: 3,
  leviticus: 3,
  números: 4,
  numbers: 4,
  deuteronômio: 5,
  deuteronomy: 5,
  josué: 6,
  joshua: 6,
  juízes: 7,
  judges: 7,
  rute: 8,
  ruth: 8,
  '1 samuel': 9,
  '2 samuel': 10,
  '1 reis': 11,
  '1 kings': 11,
  '2 reis': 12,
  '2 kings': 12,
  '1 crônicas': 13,
  '1 chronicles': 13,
  '2 crônicas': 14,
  '2 chronicles': 14,
  esdras: 15,
  ezra: 15,
  neemias: 16,
  nehemiah: 16,
  ester: 17,
  esther: 17,
  jó: 18,
  job: 18,
  salmos: 19,
  psalms: 19,
  psalm: 19,
  provérbios: 20,
  proverbs: 20,
  eclesiastes: 21,
  ecclesiastes: 21,
  cantares: 22,
  'song of solomon': 22,
  isaías: 23,
  isaiah: 23,
  jeremias: 24,
  jeremiah: 24,
  lamentações: 25,
  lamentations: 25,
  ezequiel: 26,
  ezekiel: 26,
  daniel: 27,
  oséias: 28,
  hosea: 28,
  joel: 29,
  amós: 30,
  amos: 30,
  obadias: 31,
  obadiah: 31,
  jonas: 32,
  jonah: 32,
  miquéias: 33,
  micah: 33,
  naum: 34,
  nahum: 34,
  habacuque: 35,
  habakkuk: 35,
  sofonias: 36,
  zephaniah: 36,
  ageu: 37,
  haggai: 37,
  zacarias: 38,
  zechariah: 38,
  malaquias: 39,
  malachi: 39,
  // ── Novo Testamento ─────────────────────────────────────────────────
  mateus: 40,
  matthew: 40,
  marcos: 41,
  mark: 41,
  lucas: 42,
  luke: 42,
  joão: 43,
  john: 43,
  atos: 44,
  acts: 44,
  romanos: 45,
  romans: 45,
  '1 coríntios': 46,
  '1 corinthians': 46,
  '2 coríntios': 47,
  '2 corinthians': 47,
  gálatas: 48,
  galatians: 48,
  efésios: 49,
  ephesians: 49,
  filipenses: 50,
  philippians: 50,
  colossenses: 51,
  colossians: 51,
  '1 tessalonicenses': 52,
  '1 thessalonians': 52,
  '2 tessalonicenses': 53,
  '2 thessalonians': 53,
  '1 timóteo': 54,
  '1 timothy': 54,
  '2 timóteo': 55,
  '2 timothy': 55,
  tito: 56,
  titus: 56,
  filemom: 57,
  philemon: 57,
  hebreus: 58,
  hebrews: 58,
  tiago: 59,
  james: 59,
  '1 pedro': 60,
  '1 peter': 60,
  '2 pedro': 61,
  '2 peter': 61,
  '1 joão': 62,
  '1 john': 62,
  '2 joão': 63,
  '2 john': 63,
  '3 joão': 64,
  '3 john': 64,
  judas: 65,
  jude: 65,
  apocalipse: 66,
  revelation: 66,
};

/**
 * Resolve um nome de livro (PT ou EN, com ou sem acentos preservados)
 * para o bookId canônico. Retorna null quando não reconhecido — o caller
 * decide degradar (ignorar filtro / cair no retriever híbrido).
 */
export function resolveBookId(name: string): number | null {
  const key = name.toLowerCase().replace(/\s+/g, ' ').trim();
  return BOOK_NAME_TO_ID[key] ?? null;
}
